# Generated by Django 5.0.1 on 2024-02-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
